import Phaser from 'phaser';

export const GameEvents = {
  RUN_STARTED: 'RUN_STARTED',
  PLAYER_JUMPED: 'PLAYER_JUMPED',
  PLAYER_SLID: 'PLAYER_SLID',
  COIN_COLLECTED: 'COIN_COLLECTED',
  POWERUP_PICKED: 'POWERUP_PICKED',
  POWERUP_EXPIRED: 'POWERUP_EXPIRED',
  OBSTACLE_HIT: 'OBSTACLE_HIT',
  PLAYER_DIED: 'PLAYER_DIED',
  WORLD_UNLOCKED: 'WORLD_UNLOCKED',
  GLITCH_STARTED: 'GLITCH_STARTED',
  GLITCH_ENDED: 'GLITCH_ENDED',
  BATTERY_LOW_STARTED: 'BATTERY_LOW_STARTED',
  BATTERY_LOW_ENDED: 'BATTERY_LOW_ENDED',
  WIFI_DEAD_STARTED: 'WIFI_DEAD_STARTED',
  WIFI_DEAD_ENDED: 'WIFI_DEAD_ENDED',
} as const;

export type GameEventName = (typeof GameEvents)[keyof typeof GameEvents];

export const EventBus = new Phaser.Events.EventEmitter();
